import React from "react";
import type { ComponentType } from "react";
import type { IconName } from "@/lib/types";
import {
  IconApi,
  IconApple,
  IconASM,
  IconC,
  IconColab,
  IconCV,
  IconFramer,
  IconGitBranch,
  IconGitHub,
  IconJavaLogo,
  IconJupyter,
  IconJS,
  IconKeras,
  IconLinkedIn,
  IconLinux,
  IconMail,
  IconNext,
  IconNumPy,
  IconOpenGL,
  IconPandas,
  IconPython,
  IconReact,
  IconSklearn,
  IconSpine,
  IconSQL,
  IconTailwind,
  IconTensor,
  IconVercel,
  IconVMware,
  IconVSCodeLogo,
  IconWindowsLogo,
} from "./index";

const ICON_MAP = {
  github: IconGitHub,
  linkedin: IconLinkedIn,
  mail: IconMail,
  cv: IconCV,
  spine: IconSpine,
  api: IconApi,
  python: IconPython,
  java: IconJavaLogo,
  c: IconC,
  sql: IconSQL,
  asm: IconASM,
  js: IconJS,
  next: IconNext,
  react: IconReact,
  tailwind: IconTailwind,
  framer: IconFramer,
  pandas: IconPandas,
  numpy: IconNumPy,
  sklearn: IconSklearn,
  tensor: IconTensor,
  keras: IconKeras,
  jupyter: IconJupyter,
  colab: IconColab,
  "git-branch": IconGitBranch,
  vscode: IconVSCodeLogo,
  vmware: IconVMware,
  opengl: IconOpenGL,
  vercel: IconVercel,
  windows: IconWindowsLogo,
  linux: IconLinux,
  apple: IconApple,
} as const satisfies Record<IconName, ComponentType<{ className?: string }>>;

export function IconByName({ name, className = "h-5 w-5" }: { name: IconName; className?: string }) {
  const Icon = ICON_MAP[name] ?? IconApi;
  return <Icon className={className} />;
}
